export const CALENDAR_ACTIVATE_MONTH_SELECTOR = "CALENDAR_ACTIVATE_MONTH_SELECTOR";
export const CALENDAR_ACTIVATE_YEAR_SELECTOR = "CALENDAR_ACTIVATE_YEAR_SELECTOR";
export const CALENDAR_DEACTIVATE_MONTH_SELECTOR = "CALENDAR_DEACTIVATE_MONTH_SELECTOR";
export const CALENDAR_DEACTIVATE_YEAR_SELECTOR = "CALENDAR_DEACTIVATE_YEAR_SELECTOR";

export const CALENDAR_SET_DATE = "CALENDAR_SET_DATE";
export const CALENDAR_FETCH_MOOD_REQUEST = "CALENDAR_FETCH_MOOD_REQUEST";
export const CALENDAR_FETCH_MOOD_SUCCESS = "CALENDAR_FETCH_MOOD_SUCCESS";
export const CALENDAR_FETCH_MOOD_FAIL = "CALENDAR_FETCH_MOOD_FAIL";
