export const CALENDAR_ACTIVATE_MONTH_SELECTOR = "CALENDAR_ACTIVATE_MONTH_SELECTOR";
export const CALENDAR_ACTIVATE_YEAR_SELECTOR = "CALENDAR_ACTIVATE_YEAR_SELECTOR";
export const CALENDAR_DEACTIVATE_MONTH_SELECTOR = "CALENDAR_DEACTIVATE_MONTH_SELECTOR";
export const CALENDAR_DEACTIVATE_YEAR_SELECTOR = "CALENDAR_DEACTIVATE_YEAR_SELECTOR";
export const CALENDAR_SET_YEAR = "CALENDAR_SET_YEAR";
export const CALENDAR_SET_MONTH = "CALENDAR_SET_MONTH";
export const CALENDAR_SET_DATE = "CALENDAR_SET_DATE";
export const CALENDAR_SET_ALL = "CALENDAR_SET_ALL";