export const CALENDAR_ACTIVATE_MONTH_SELECTOR = "CALENDAR_ACTIVATE_MONTH_SELECTOR";
export const CALENDAR_ACTIVATE_YEAR_SELECTOR = "CALENDAR_ACTIVATE_YEAR_SELECTOR";
export const CALENDAR_DEACTIVATE_MONTH_SELECTOR = "CALENDAR_DEACTIVATE_MONTH_SELECTOR";
export const CALENDAR_DEACTIVATE_YEAR_SELECTOR = "CALENDAR_DEACTIVATE_YEAR_SELECTOR";

export const CALENDAR_SET_DATE = "CALENDAR_SET_DATE";
