export const DIARY_FETCH_REQUEST = "DIARY_FETCH_REQUEST";
export const DIARY_FETCH_FAIL = "DIARY_FETCH_FAIL";
export const DIARY_FETCH_SUCCESS = "DIARY_FETCH_SUCCESS";

export const DIARY_SET_DATE = "DIARY_SET_DATE";
export const DIARY_SET_ALL = "DIARY_SET_ALL";

export const DIARY_ACTIVATE_IMAGE = "DIARY_ACTIVATE_IMAGE";
export const DIARY_DEACTIVATE_IMAGE = "DIARY_DEACTIVATE_IMAGE";

export const DIARY_INPUT_REQUEST = "DIARY_INPUT_REQUEST";
export const DIARY_INPUT_FAIL = "DIARY_INPUT_FAIL";
export const DIARY_INPUT_SUCCESS = "DIARY_INPUT_SUCCESS";